### ISSUE TITLE
Sync getting stuck at block 5bf013e8412835db45d5506cf505ccd60e491dc73b2d4ffda49ebaf18d8e9d74 in epoch 383 ?

### ISSUE THREAD

**Issue by stake1edge** [dcSpark/carp#127]
I believe there is a problematic tx not getting parsed within this block itself. This was produced from a fresh install, no modifications to execution plan and with latest versions Carp (2.1.0), PostgreSQL (14.5).

Message I receive ~20+ times before it crashes:
```
2023-01-19T00:12:41.476703Z  INFO carp::postgres_sink: Rolling back to block 5bf013e8412835db45d5506cf505ccd60e491dc73b2d4ffda49ebaf18d8e9d74 at slot 80233874
2023-01-19T00:12:41.477478Z  WARN oura::utils::retry: retryable operation error: DownstreamError(Error { err: Message, pos: None, msg: "bad cbor data type for plutus data" })
```

Full trace of the issue:
```thread '<unnamed>' panicked at 'attempt to multiply with overflow', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/num/mod.rs:918:5
stack backtrace:
0:     0x560f27eeee30 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
1:     0x560f27eeee30 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2:     0x560f27eeee30 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
3:     0x560f27eeee30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
4:     0x560f27f12a8e - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
5:     0x560f27ee99e5 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
6:     0x560f27eeebf5 - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
7:     0x560f27eeebf5 - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
8:     0x560f27ef04af - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
9:     0x560f27ef01ea - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
10:     0x560f27ef0ba8 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5                                                                                                       
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
11:     0x560f27ef0901 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:577:13
12:     0x560f27eef2dc - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
13:     0x560f27ef0662 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
14:     0x560f26b52fa3 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
15:     0x560f26b5307d - core::panicking::panic::h9ced3cf2f605ba6a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
16:     0x560f273e2e4b - core::num::<impl u32>::pow::hc39e2d7e25ca8680
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/num/uint_macros.rs:1935:24
17:     0x560f2738f45a - oura::utils::retry::compute_backoff_delay::he15aa207fe03f7a5
                               at /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.7.3/src/utils/retry.rs:39:17
18:     0x560f2738f7e5 - oura::utils::retry::retry_operation::h1015e60800f163d7
                               at /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.7.3/src/utils/retry.rs:60:31
19:     0x560f27385a44 - oura::sources::n2c::run::do_chainsync::hd810531b645d151e
                               at /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.7.3/src/sources/n2c/run.rs:230:5
20:     0x560f2739db9b - oura::sources::n2c::setup::<impl oura::pipelining::SourceProvider for oura::utils::WithUtils<oura::sources::n2c::setup::Config>>::bootstrap::{{closure}}::h6f8707a71a7
5854c
                               at /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.7.3/src/sources/n2c/setup.rs:55:13
21:     0x560f2738aa7f - std::sys_common::backtrace::__rust_begin_short_backtrace::hbd32cb8167fc7d5c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
22:     0x560f273ea9c0 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::he1586654fd90a486
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:551:17
23:     0x560f273a0b64 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf8b798e8e918bfed
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panic/unwind_safe.rs:271:9
24:     0x560f273f1400 - std::panicking::try::do_call::hd0b02fce89109867
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
25:     0x560f273fd83b - __rust_try
26:     0x560f273f112c - std::panicking::try::h4a72fa8c5c4d222a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
27:     0x560f273f0fd4 - std::panic::catch_unwind::hcf1d6ed69763f357
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
28:     0x560f273ea783 - std::thread::Builder::spawn_unchecked_::{{closure}}::ha66a63d1fbd9c480
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:550:30
29:     0x560f273f1b5f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h651448ce724c4c34
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
30:     0x560f27ef3753 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4273f95ec44459b3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
31:     0x560f27ef3753 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70f28fa4ddc269e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
32:     0x560f27ef3753 - std::sys::unix::thread::Thread::new::thread_start::h85a9c16b988e2bd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
33:     0x7fd75fae6b43 - <unknown>
34:     0x7fd75fb78a00 - <unknown>
35:                0x0 - <unknown>
Error: receiving on a closed channel```

**Comment by gostkin** [comment]
which cardano node version are you using?

**Comment by stake1edge** [comment]
Ok cool. It was latest cardano-node 1.35.4
