### ISSUE TITLE
Error occurred while decoding: Null

### ISSUE THREAD

**Issue by liv-io** [dcSpark/carp#182]
I am not able to start a fresh carp 3.0.1 instance in `preprod`. After applying all migrations, carp exits with the following error message:
```
Applying all pending migrations
...
Migration 'm20240229_000019_add_block_tx_count_column' has been applied
2024-03-28T14:12:32.705102Z  INFO carp::sinks::cardano: Starting epoch 0 at block #1 (1d031daf47281f69cd95ab929c269fd26b1434a56a5bbbd65b7afe85ef96b233)
thread '<unnamed>' panicked at indexer/tasks/src/byron/byron_block.rs:11:1:
called `Result::unwrap()` on an `Err` value: Query("error occurred while decoding: Null")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /root/.cargo/git/checkouts/oura-651309f44306a5e9/27fb7e8/src/filters/selection.rs:235:43:
error sending filter message: SendError { .. }
thread '<unnamed>' panicked at /root/.cargo/git/checkouts/oura-651309f44306a5e9/27fb7e8/src/mapper/prelude.rs:78:14:
```

My setup consists of:
- Debian 12
- cardano-node 8.7.3
- postgresql 15

I also tried cardano-node 8.9.1 without success. Carp 2.4.0 works flawlessly with the exact same setup and configuration.
Please find my `default.yml` configuration file below:
```
source:
  type: oura
  socket: "/var/local/cardano-node/db/node.socket"
  bearer: Unix # Unix
sink:
  type: cardano
  db:
    type: postgres
    database_url: postgresql://carp:carp@localhost:5432/carp
  network: preprod # preview / preprod / testnet
start_block:
```

Any inputs are highly appreciated. Thanks!

**Comment by ironmask285** [comment]
:( I got same issue
