### ISSUE TITLE
Investigate "could not extend file" crash

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/carp#52]
Got this crash. Haven't had the time to investigate it yet so I'm keeping it here to track this

Thought: may be caused by reaching the tip when cardano-node crashed due to clock skew error

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Query("error returned from database: could not extend file \"base/12393824/12393930.1\": wrote only 4096 of 8192 bytes at block 254639")', tasks/src/multiera/multiera_outputs.rs:101:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018:23
   4: <tasks::multiera::multiera_outputs::MultieraOutputTask as shred::system::System>::run
             at ./tasks/src/multiera/multiera_outputs.rs:93:22
   5: <T as shred::system::RunNow>::run_now
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.12.0/src/system.rs:140:9
   6: shred::dispatch::stage::Stage::execute::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.12.0/src/dispatch/stage.rs:111:17
   7: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:247:13
   8: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/slice/iter/macros.rs:211:21
   9: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/for_each.rs:55:9
  10: rayon::iter::plumbing::Producer::fold_with
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:110:9
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:438:13
  12: rayon::iter::plumbing::bridge_producer_consumer
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:397:12
  13: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:373:13
  14: <rayon::slice::IterMut<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/slice/mod.rs:727:9
  15: rayon::iter::plumbing::bridge
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:357:12
  16: <rayon::slice::IterMut<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/slice/mod.rs:703:9
  17: rayon::iter::for_each::for_each
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/for_each.rs:12:5
  18: rayon::iter::ParallelIterator::for_each
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/mod.rs:369:9
  19: shred::dispatch::stage::Stage::execute
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.12.0/src/dispatch/stage.rs:109:9
  20: shred::dispatch::dispatcher::Dispatcher::dispatch_par::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.12.0/src/dispatch/dispatcher.rs:89:21
  21: rayon_core::thread_pool::ThreadPool::install::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/thread_pool/mod.rs:111:40
  22: rayon_core::registry::Registry::in_worker_cold::{{closure}}::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/registry.rs:467:21
  23: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/job.rs:113:21
  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  25: std::panicking::try::do_call
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  26: __rust_try
  27: std::panicking::try
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  28: std::panic::catch_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  29: rayon_core::unwind::halt_unwinding
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/unwind.rs:17:5
  30: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/job.rs:119:38
  31: rayon_core::job::JobRef::execute
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/job.rs:59:9
  32: rayon_core::registry::WorkerThread::execute
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/registry.rs:751:9
  33: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/registry.rs:728:17
  34: rayon_core::registry::WorkerThread::wait_until
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/registry.rs:702:13
  35: rayon_core::registry::main_loop
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/registry.rs:835:5
  36: rayon_core::registry::ThreadBuilder::run
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/registry.rs:55:18
  37: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.2/src/registry.rs:100:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'error sending filter message: SendError { .. }', /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/filters/selection.rs:111:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::expect
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:975:23
   4: <oura::filters::selection::Config as oura::pipelining::FilterProvider>::bootstrap::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/filters/selection.rs:111:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'error sending event through output stage, pipeline must have crashed.: SendError { .. }', /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/prelude.rs:78:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::expect
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:975:23
   4: oura::mapper::prelude::EventWriter::append
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/prelude.rs:76:9
   5: oura::mapper::prelude::EventWriter::append_from
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/prelude.rs:87:9
   6: oura::mapper::shelley::<impl oura::mapper::prelude::EventWriter>::crawl_transaction_output_amount
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/shelley.rs:80:21
   7: oura::mapper::shelley::<impl oura::mapper::prelude::EventWriter>::crawl_transaction_output
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/shelley.rs:105:9
   8: oura::mapper::shelley::<impl oura::mapper::prelude::EventWriter>::crawl_shelley_transaction
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/shelley.rs:193:25
   9: oura::mapper::shelley::<impl oura::mapper::prelude::EventWriter>::crawl_shelley_block
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/shelley.rs:263:13
  10: oura::mapper::shelley::<impl oura::mapper::prelude::EventWriter>::crawl_shelley_with_cbor
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/mapper/shelley.rs:324:9
  11: <oura::sources::n2c::run::ChainObserver as pallas_miniprotocols::chainsync::agents::Observer<pallas_miniprotocols::chainsync::protocol::BlockContent>>::on_roll_forward
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/sources/n2c/run.rs:68:64
  12: pallas_miniprotocols::chainsync::agents::Consumer<C,O>::on_roll_forward
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/pallas-miniprotocols-0.9.1/src/chainsync/agents.rs:121:28
  13: <pallas_miniprotocols::chainsync::agents::Consumer<C,O> as pallas_miniprotocols::machines::Agent>::apply_inbound
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/pallas-miniprotocols-0.9.1/src/chainsync/agents.rs:217:17
  14: pallas_miniprotocols::machines::run_agent_step
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/pallas-miniprotocols-0.9.1/src/machines.rs:158:13
  15: pallas_miniprotocols::machines::run_agent
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/pallas-miniprotocols-0.9.1/src/machines.rs:173:17
  16: oura::sources::n2c::run::observe_forever
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/sources/n2c/run.rs:123:17
  17: oura::sources::n2c::setup::<impl oura::pipelining::SourceProvider for oura::utils::WithUtils<oura::sources::n2c::setup::Config>>::bootstrap::{{closure}}
             at /home/sebdev20/.cargo/registry/src/github.com-1ecc6299db9ec823/oura-1.4.1/src/sources/n2c/setup.rs:102:13
```

**Comment by rinor** [comment]
This is the database (postgres in this case) reporting back that it has run out of shared memory. Increasing the available shared memory for postgres will get rid of the error
